name: CI Light (Feature → Develop)

on:
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["develop", "main"]

permissions:
  contents: read

jobs:
  verify-light:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Block feature -> main PRs (safety)
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          echo "Blocking feature -> main: use feature->develop->release->main." >&2
          exit 1

      - name: Prettier check (light)
        run: npx prettier --check "**/*.{js,html,css,md,json}"

      - name: Quick site verification
        run: |
          test -f site/index.html
          echo "✅ Site files exist"
