name: CI Medium (Develop → Release)

on:
  push:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  verify-medium:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Prettier check
        run: npx prettier --check "**/*.{js,html,css,md,json}"

      - name: Design system lint
        run: npm run -s lint:design

      - name: Visual regression tests (quick - conditional)
        shell: bash
        run: |
          if [ -d tests/visual ] && find tests/visual -type f -name "*spec.*" | grep -q .; then
            npm run test:quick
          else
            echo "No visual tests found. Skipping."
          fi

      - name: Sanity check - site exists
        run: |
          test -f site/index.html
          ls -la site

      - name: Sanity check - dataset size budget (<= 60MB)
        run: |
          node -e "const fs=require('fs'); const p='site/data/enhanced_latest.json'; if(fs.existsSync(p)){const s=fs.statSync(p).size; if(s>60*1024*1024){throw new Error('enhanced_latest.json too large: '+s)}}"
